chart/urls.py
from django.urls import path

from .views import *
from chart import views
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.conf import settings



app_name = 'chart'

urlpatterns = [
    path('', home, name='home'),
    path('ticket-class/3/',
         ticket_class_view_3, name='ticket_class_view_3'),
    path('covid-confirmed/', covid_confirmed, name='covid_confirmed'),
    path('covid-recovered/', covid_recovered, name='covid_recovered'),
    path('covid-deaths/', covid_deaths, name='covid_deaths'),

]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from chart import views as chart
from django.conf.urls.static import static
from django.conf.urls import  include, url
from django.conf import settings


urlpatterns = [
	path('', chart.home, name='home'),
    path('chart/', include('chart.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.18.0/css/mdb.min.css" rel="stylesheet">
    {% load static %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <nav class="mb-1 navbar navbar-expand-lg navbar-dark secondary-color lighten-1">
  <a class="navbar-brand" href="/">장고 앱 모음</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
    aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'chart:covid_confirmed' %}">
           확진자 현황
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'chart:covid_recovered' %}">
           회복자 현황</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'chart:covid_deaths' %}">
           사망자 현황</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'chart:ticket_class_view_3' %}">
           타이타닉</a>
      </li>

    </ul>
  </div>
</nav>
<!--/.Navbar -->


    <div class="row">
        <div class="col">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <!-- Footer -->
<footer class="page-footer font-small secondary-color lighten-1">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://ddadcdcovid.pythonanywhere.com/"> ddadcdcovid.pythonanywhere.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
</div>
</body>
</html>